# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "Default" -Configuration "Release"

# Tests
test: off

# Build cache
cache:
- tools -> build.cake